// Symbols generated by assembly code. Can be viewed in the Symbol table in AssemblyResults
package sic_xe_assembler;

public class Symbol {

    String data;
    String name;
    String type;
    int size;
    
    public Symbol(String name, String data, String type)
    {
        this.name = name;
        this.data = data;
        this.type = type;
    }
    
    public Symbol(String name, int size, String type)
    {
        this.name = name;
        this.size = size;
        this.type = type;
    }
}
