// Symbols generated by assembly code. Can be viewed in the Symbol table in AssemblyResults
package sic_xe_assembler;

public class Symbol {
    int size;
    String data;
    String name;
    
    public Symbol(String name, int size, String data)
    {
        this.name=name;
        this.size=size;
        this.data=data;
    }
}
